# Page settings

baseurl = "https://Alekssasho.github.io/resume/"
languageCode = "en-us"
title = "Aleksandar Angelov Resume"
theme = "orbit"
googleAnalytics = "UA-132338357-1"
publishdir = "../public/resume"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV"
    author = "Aleksandar Angelov"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-4.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Aleksandar Angelov"
        tagline = "Software Developer / Team Lead"
        avatar = "profile@150.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: aleksandar.angelovv@gmail.com"
        title = "aleksandar.angelovv@gmail.com"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//Alekssasho.github.io"
        title = "Alekssasho.github.io"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//www.linkedin.com/in/aleksandar-angelov-b1a99251/"
        title = "LinkedIn Profile"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/Alekssasho"
        title = "github.com/Alekssasho"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/Alekssasho"
        title = "@Alekssasho"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc in Computer Graphics"
        college = "University of Sofia - Faculty of Mathematics and Informatics"
        dates = "2017 - 2019"

        [[params.education.list]]
        degree = "BSc in Computer Science"
        college = "University of Sofia - Faculty of Mathematics and Informatics"
        dates = "2013 - 2017"

        [[params.education.list]]
        degree = "System Programming"
        college = "Technology School Electronic Systems - Elsys"
        dates = "2008 - 2013"

    # Languages section
    [params.language]
        enable = false
        title = "Languages"

        [[params.language.list]]
        language = "Bulgarian"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = false
        icon = "fa-user"
        title = "Career Profile"
        summary = "???"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Team Lead"
        dates = "Oct 2020 - Present"
        company = "Chaos Group, Sofia"
        details = "Team Lead of V-Ray GPU team working on in-house GPU production render engine. Team management, product management."

        [[params.jobs.list]]
        position = "Senior Software Developer"
        dates = "Apr 2019 - Oct 2020"
        company = "Chaos Group, Sofia"
        details = "Developing in house GPU renderer - V-Ray GPU. Implement features like Matte/Shadow Catchers, Displaced 2d geometry in V-Ray GPU. Implemented RTX features inside V-Ray GPU."

        [[params.jobs.list]]
        position = "Senior Graphics Developer"
        dates = "Oct 2018 - Mar 2019"
        company = "Coherent Labs, Sofia"
        details = "Mentoring junior developers. R&D in 3D User Interfaces. Responsible for in-house debugging tools. Working directly with clients to resolve performance and usability issues."

        [[params.jobs.list]]
        position = "Graphics Developer"
        dates = "Feb 2015 - Sep 2018"
        company = "Coherent Labs, Sofia"
        details = "Developing Core 2D Rendering in-house library used in all products of the company. Researching & developing different 2D rendering algorithm for text, vector graphics, CSS3 effects like shadows and filters. Ported WebCore to use our rendering library. Implemented and improved various graphics API backends."

        [[params.jobs.list]]
        position = "Junior iOS Developer"
        dates = "Apr 2013 - Jan 2015"
        company = "Openintegra, Sofia"
        details = "Developing multiple in-house iOS application. Used technologies - Objective-C, XCode"

        [[params.jobs.list]]
        position = "Intern"
        dates = "Jul 2012 - Aug 2012"
        company = "Haemimont Games, Sofia"
        details = "Writing a simple 2D game with Lua."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = ""

        [[params.projects.list]]
        title = "Graphics Prototypes"
        url = "https://github.com/Alekssasho/GraphicsPrototypes"
        tagline = "Repo with 3D Graphics experiments and prototypes using Falcor. Masters Thesis work for a Real-Time  Diffuse Global Illumination algorithm based on Pica Pica's algorithm for GI."

        [[params.projects.list]]
        title = "Co-Teacher/Author"
        url = "https://github.com/nikoladimitroff/Game-Engine-Architecture"
        tagline = "Co-Teacher of a course about Game Engine Architecture in Sofia University. All slides are public. The theory is about how a game engine is structured with examples from Unreal Engine 4 codebase."

        [[params.projects.list]]
        title = "Tempo Engine"
        url = "https://github.com/Alekssasho/TempoEngine/"
        tagline = "Game engine from scratch in very early stages. Runtime is C++, tooling and asset pipeline in Rust."

        [[params.projects.list]]
        title = "Warlocks"
        url = "https://gitlab.com/Alekssasho/warlocks"
        tagline = "UE4 multiplayer brawler arena game. Responsible for Gameplay abilities and animation/graphics support."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "C++"
        level = "98%"
                
        [[params.skills.list]]
        skill = "GPU Programming"
        level = "90%"

        [[params.skills.list]]
        skill = "Graphics APIs"
        level = "95%"

        [[params.skills.list]]
        skill = "Shader Languages"
        level = "92%"

        [[params.skills.list]]
        skill = "Git"
        level = "80%"

        [[params.skills.list]]
        skill = "CUDA"
        level = "80%"

        [[params.skills.list]]
        skill = "PS4/XB1/Switch Programming"
        level = "75%"

        [[params.skills.list]]
        skill = "Rust"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Aleksandar Angelov"
