baseurl = "https://Alekssasho.github.io/"
languageCode = "en-us"
title = "Alekssasho's Blog"
theme = "hello-friend"
copyright = ""
googleAnalytics = "UA-132338357-1"
paginate = 5
publishdir = "../public"

[params]
  subtitle = ""
  # "light" or "dark"
  defaultTheme = "dark"
  twitterlink = "https://twitter.com/Alekssasho"
  githublink = "https://github.com/Alekssasho"
  linkedinlink = "https://www.linkedin.com/in/aleksandar-angelov-b1a99251/"
  maillink = "aleksandar.angelovv@gmail.com"

[params.logo]
  logoText = "Rendering Pixels"
#   or
#
#   path = "/img/your-example-logo.svg"
#   alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 3
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume"
    weight = 2
